/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tray_linux_NativeLinuxTray */

#ifndef _Included_tray_linux_NativeLinuxTray
#define _Included_tray_linux_NativeLinuxTray
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tray_linux_NativeLinuxTray
 * Method:    nativeInit0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tray_linux_NativeLinuxTray_nativeInit0
  (JNIEnv *, jobject);

/*
 * Class:     tray_linux_NativeLinuxTray
 * Method:    nativeCreateTrayIcon0
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_tray_linux_NativeLinuxTray_nativeCreateTrayIcon0
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     tray_linux_NativeLinuxTray
 * Method:    nativeRemoveMe0
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_tray_linux_NativeLinuxTray_nativeRemoveMe0
  (JNIEnv *, jobject, jint);

/*
 * Class:     tray_linux_NativeLinuxTray
 * Method:    nativeAddMenuItem0
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_tray_linux_NativeLinuxTray_nativeAddMenuItem0
  (JNIEnv *, jobject, jint, jint, jstring);

/*
 * Class:     tray_linux_NativeLinuxTray
 * Method:    nativeSetImage0
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_tray_linux_NativeLinuxTray_nativeSetImage0
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     tray_linux_NativeLinuxTray
 * Method:    nativeGetIconLocation0
 * Signature: (I)Ljava/awt/Point;
 */
JNIEXPORT jobject JNICALL Java_tray_linux_NativeLinuxTray_nativeGetIconLocation0
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
